# Generated by Django 4.1.7 on 2023-05-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_alter_categorie_name_alter_produit_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='Fournisseur',
            new_name='fournisseur',
        ),
    ]
